#!/usr/bin/env bash
set -euo pipefail

# This script sets up a Debian 13 GNOME Wayland VM environment for neugaze development.
# It prepares the disk image and ISO, detects USB cameras for passthrough, and can optionally launch the VM installer.
# ~/vm-images/debian13-gnome-wayland.qcow2 will be created if it doesn't exist, and the Debian netinst ISO will be downloaded if not present.
# ~/vm-images/neugaze-ready-debian13.qcow2 will be created if it doesn't exist, and the Debian netinst ISO will be downloaded if not present.
VM_NAME=${VM_NAME:-neugaze-debian13}
IMAGE_DIR=${IMAGE_DIR:-/var/lib/libvirt/images/neugaze}
ISO_NAME=${ISO_NAME:-debian-13.5.0-amd64-netinst.iso}
ISO_URL=${ISO_URL:-https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/$ISO_NAME}
#DISK_NAME=${DISK_NAME:-debian13-gnome-wayland.qcow2}
DISK_NAME=${DISK_NAME:-neugaze-ready-debian13.qcow2}
DISK_SIZE=${DISK_SIZE:-30G}
RAM=${RAM:-8192}
VCPUS=${VCPUS:-4}
OS_VARIANT=${OS_VARIANT:-debian13}
GRAPHICS=${GRAPHICS:-spice}
VIDEO=${VIDEO:-qxl}
CAMERA_VENDOR_ID=${CAMERA_VENDOR_ID:-}
CAMERA_PRODUCT_ID=${CAMERA_PRODUCT_ID:-}
AUTO_DETECT_CAMERA=${AUTO_DETECT_CAMERA:-true}
NEUGAZE_VM_USERNAME=${NEUGAZE_VM_USERNAME:-neugaze-user}
NEUGAZE_VM_USER_PASSWORD=${NEUGAZE_VM_USER_PASSWORD:-neugaze-user-password}


show_help() {
  cat <<'EOF'
Usage: neugaze-vm-setup.sh [--help]

Creates a Debian 13 GNOME Wayland VM environment for neugaze development.
Run without arguments to perform a fully automated one-step setup:
  - Downloads the Debian netinstall ISO if not present.
  - Creates a QCOW2 disk image if not present.
  - Installs Debian with a minimal GNOME desktop, all neugaze build dependencies, and rustup
    via preseeded automation.
  - If Debian is already installed on the disk, boots it instead.

Environment variables:
  CAMERA_VENDOR_ID      USB camera vendor ID to passthrough to QEMU.
  CAMERA_PRODUCT_ID     USB camera product ID to passthrough to QEMU.
  AUTO_DETECT_CAMERA    When true, auto-detect a single USB camera if no IDs are provided.
  NEUGAZE_VM_USERNAME           Username created in the VM (default: neugaze-user).
  NEUGAZE_VM_USER_PASSWORD      Password for NEUGAZE_VM_USERNAME (default: neugaze-user-password).
EOF
}

ensure_command() {
  local cmd=$1
  command -v "$cmd" >/dev/null 2>&1 || {
    echo "Error: required command '$cmd' not found." >&2
    exit 1
  }
}

normalize_id() {
  local id=$1
  if [[ -z "$id" ]]; then
    echo
    return
  fi
  if [[ "$id" == 0x* ]]; then
    echo "$id"
  else
    echo "0x$id"
  fi
}

detect_installed_debian() {
  local image=$1
  if ! command -v guestfish >/dev/null 2>&1; then
    return 1
  fi
  echo 'cat /etc/debian_version' | guestfish --ro -a "$image" -i 2>/dev/null | grep -q '.'
}

detect_camera() {
  local matches line count index choice
  matches=$(lsusb | grep -Ei 'camera|webcam|video|uvc|face|stream' || true)
  if [[ -z "$matches" ]]; then
    return 1
  fi

  count=$(printf '%s\n' "$matches" | grep -c '^')
  if [[ $count -eq 1 ]]; then
    line="$matches"
  else
    echo "Multiple USB video devices detected:" >&2
    index=1
    while IFS= read -r line; do
      printf '  %d) %s\n' "$index" "$line" >&2
      index=$((index + 1))
    done <<<"$matches"

    if [[ -t 0 ]]; then
      echo -n "Choose a device to passthrough [1-$count] (or press Enter to skip): " >&2
      read -r choice
      if [[ -z "$choice" ]]; then
        return 2
      fi
      if ! [[ "$choice" =~ ^[0-9]+$ ]] || (( choice < 1 )) || (( choice > count )); then
        echo "Invalid selection." >&2
        return 2
      fi
      line=$(printf '%s\n' "$matches" | sed -n "${choice}p")
    else
      echo "Please set CAMERA_VENDOR_ID and CAMERA_PRODUCT_ID explicitly." >&2
      return 2
    fi
  fi

  if [[ "$line" =~ ID[[:space:]]([0-9a-fA-F]{4}):([0-9a-fA-F]{4}) ]]; then
    CAMERA_VENDOR_ID="0x${BASH_REMATCH[1]}"
    CAMERA_PRODUCT_ID="0x${BASH_REMATCH[2]}"
    return 0
  fi

  return 1
}

# ---------------------------------------------------------------------------
# Automated install helpers
# ---------------------------------------------------------------------------

find_free_port() {
  python3 -c 'import socket; s=socket.socket(); s.bind(("",0)); p=s.getsockname()[1]; s.close(); print(p)'
}

HTTP_PID=""

start_http_server() {
  local port="$1"
  python3 -m http.server "$port" --directory "$IMAGE_DIR" >/dev/null 2>&1 &
  HTTP_PID=$!
  # Give the server a moment to bind before QEMU starts
  sleep 1
}

stop_http_server() {
  if [[ -n "$HTTP_PID" ]]; then
    kill "$HTTP_PID" 2>/dev/null || true
    HTTP_PID=""
  fi
}

# Write a Debian preseed.cfg into IMAGE_DIR.
# $1 = HTTP port on the host (served at 10.0.2.2:PORT from within QEMU user-net)
generate_preseed() {
  local port="$1"
  cat > "$IMAGE_DIR/preseed.cfg" <<PRESEED
# Automated Debian 13 preseed — neugaze development VM
# Generated by neugaze-vm-setup.sh

### Localisation
d-i debian-installer/locale string en_US.UTF-8
d-i console-setup/ask_detect boolean false
d-i keyboard-configuration/xkb-keymap select us

### Network
d-i netcfg/choose_interface select auto
d-i netcfg/get_hostname string neugaze-dev
d-i netcfg/get_domain string local

### Mirror
d-i mirror/country string manual
d-i mirror/http/hostname string deb.debian.org
d-i mirror/http/directory string /debian
d-i mirror/http/proxy string

### Clock
d-i clock-setup/utc boolean true
d-i time/zone string UTC
d-i clock-setup/ntp boolean true

### Accounts — root disabled; user is added to sudo automatically
d-i passwd/root-login boolean false
d-i passwd/user-fullname string Neugaze User
d-i passwd/username string ${NEUGAZE_VM_USERNAME}
d-i passwd/user-password password ${NEUGAZE_VM_USER_PASSWORD}
d-i passwd/user-password-again password ${NEUGAZE_VM_USER_PASSWORD}

### Partitioning — guided LVM, whole disk
d-i partman-auto/method string lvm
d-i partman-auto-lvm/guided_size string max
d-i partman-auto/choose_recipe select atomic
d-i partman-lvm/device_remove_lvm boolean true
d-i partman-md/device_remove_md boolean true
d-i partman-lvm/confirm boolean true
d-i partman-lvm/confirm_nooverwrite boolean true
d-i partman/confirm_write_new_label boolean true
d-i partman/choose_partition select finish
d-i partman/confirm boolean true
d-i partman/confirm_nooverwrite boolean true

### Minimal GNOME desktop + neugaze build dependencies
tasksel tasksel/first multiselect standard
d-i base-installer/install-recommends boolean false
d-i pkgsel/include string sudo network-manager gnome-core build-essential pkg-config clang libclang-dev libopencv-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgtk-4-dev libadwaita-1-dev libglib2.0-dev libssl-dev curl git openssh-server
d-i pkgsel/upgrade select full-upgrade
d-i pkgsel/update-policy select none

### GRUB
d-i grub-installer/only_debian boolean true
d-i grub-installer/with_other_os boolean false
d-i grub-installer/bootdev string default

### Late command: fetch and run the rustup setup script
d-i preseed/late_command string wget -qO /target/tmp/neugaze-setup.sh http://10.0.2.2:${port}/neugaze-setup.sh && chmod +x /target/tmp/neugaze-setup.sh && in-target /tmp/neugaze-setup.sh

### Reboot when done
d-i debian-installer/exit/poweroff boolean true
d-i finish-install/reboot_in_progress note
PRESEED
}

# Write a post-install setup script (installs rustup for the primary user).
generate_devsetup_script() {
  cat > "$IMAGE_DIR/neugaze-setup.sh" <<'SETUP'
#!/bin/bash
set -eu
# Determine the uid-1000 user created by the installer
DEV_USER=$(getent passwd 1000 | cut -d: -f1 || true)
if [[ -z "$DEV_USER" ]]; then
  echo "neugaze-setup: could not find uid-1000 user; skipping rustup install." >&2
  exit 0
fi
echo "neugaze-setup: installing rustup for $DEV_USER ..."
su - "$DEV_USER" -c \
  'curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable --profile minimal'
echo "neugaze-setup: done."
SETUP
  chmod +x "$IMAGE_DIR/neugaze-setup.sh"
}

# Extract vmlinuz + initrd.gz from the netinstall ISO into a temp dir.
# Prints the directory path on success.
extract_installer_kernel() {
  local iso="$1"
  local out_dir="$IMAGE_DIR/.installer-boot"
  sudo mkdir -p "$out_dir"

  local sz
  if command -v 7zz >/dev/null 2>&1; then
    sz=7zz
  elif command -v 7z >/dev/null 2>&1; then
    sz=7z
  else
    echo "Error: 7zz/7z not found; install the '7zip' package." >&2
    return 1
  fi

  # -e extracts without recreating directory structure
  sudo "$sz" e -o"$out_dir" "$iso" install.amd/vmlinuz install.amd/initrd.gz -y >/dev/null

  if [[ ! -f "$out_dir/vmlinuz" || ! -f "$out_dir/initrd.gz" ]]; then
    echo "Error: could not extract vmlinuz/initrd.gz from $iso." >&2
    return 1
  fi
  echo "$out_dir"
}

# Run the fully automated Debian install.
run_auto_install() {
  ensure_command python3
  ensure_command qemu-system-x86_64

  local port
  port=$(find_free_port)

  echo "[auto] Generating preseed.cfg and post-install script (HTTP port: $port) ..."
  generate_preseed "$port"
  generate_devsetup_script

  echo "[auto] Extracting installer kernel from $ISO_NAME ..."
  local boot_dir
  boot_dir=$(extract_installer_kernel "$IMAGE_DIR/$ISO_NAME")

  echo "[auto] Starting HTTP server on port $port ..."
  start_http_server "$port"
  trap stop_http_server EXIT INT TERM

  local kernel_append="auto=true priority=critical url=http://10.0.2.2:${port}/preseed.cfg quiet"

  local -a camera_args=()
  if [[ -n "$CAMERA_VENDOR_ID" && -n "$CAMERA_PRODUCT_ID" ]]; then
    camera_args=(-device "usb-host,vendorid=$CAMERA_VENDOR_ID,productid=$CAMERA_PRODUCT_ID")
  fi

  echo "[auto] Launching automated installer (this will take a while) ..."
  sudo qemu-system-x86_64 \
    -name "$VM_NAME" \
    -machine accel=kvm \
    -cpu host \
    -smp "$VCPUS" \
    -m "$RAM" \
    -drive "file=$IMAGE_DIR/$DISK_NAME,if=virtio,format=qcow2" \
    -display gtk \
    -vga qxl \
    -nic user,model=virtio,hostfwd=tcp:127.0.0.1:2222-:22 \
    -device qemu-xhci \
    "${camera_args[@]}" \
    -cdrom "$IMAGE_DIR/$ISO_NAME" \
    -no-reboot \
    -kernel "$boot_dir/vmlinuz" \
    -initrd "$boot_dir/initrd.gz" \
    -append "$kernel_append"

  stop_http_server
  echo "[auto] Install complete. Disk: $IMAGE_DIR/$DISK_NAME"
}

for arg in "$@"; do
  case $arg in
    --help|-h)
      show_help
      exit 0
      ;;
    *)
      echo "Unknown option: $arg" >&2
      show_help
      exit 1
      ;;
  esac
done

ensure_command qemu-img
ensure_command wget
ensure_command qemu-system-x86_64
ensure_command lsusb

if ! mkdir -p "$IMAGE_DIR" 2>/dev/null; then
  sudo mkdir -p "$IMAGE_DIR"
fi
cd "$IMAGE_DIR"

echo "[1/4] Preparing VM image directory: $IMAGE_DIR"

if [[ ! -f "$ISO_NAME" ]]; then
  echo "[2/4] Downloading Debian netinst ISO: $ISO_NAME"
  sudo wget -N "$ISO_URL"
else
  echo "[2/4] ISO already exists: $ISO_NAME"
fi

if [[ ! -f "$DISK_NAME" ]]; then
  echo "[3/4] Creating QCOW2 disk: $DISK_NAME ($DISK_SIZE)"
  sudo qemu-img create -f qcow2 "$DISK_NAME" "$DISK_SIZE"
else
  echo "[3/4] Disk already exists: $DISK_NAME"
fi

if [[ -z "$CAMERA_VENDOR_ID" && -z "$CAMERA_PRODUCT_ID" && "$AUTO_DETECT_CAMERA" == "true" ]]; then
  if detect_camera; then
    echo "[4/4] Auto-detected USB camera: vendor=$CAMERA_VENDOR_ID product=$CAMERA_PRODUCT_ID"
  else
    echo "[4/4] No single USB camera auto-detected; attach a camera or set CAMERA_VENDOR_ID/CAMERA_PRODUCT_ID." >&2
  fi
fi

CAMERA_VENDOR_ID=$(normalize_id "$CAMERA_VENDOR_ID")
CAMERA_PRODUCT_ID=$(normalize_id "$CAMERA_PRODUCT_ID")

IMAGE_INSTALLED=false
if [[ -f "$DISK_NAME" ]]; then
  if ! command -v guestfish >/dev/null 2>&1; then
    echo "[5/5] guestfish not installed; skipping Debian install detection."
  elif detect_installed_debian "$IMAGE_DIR/$DISK_NAME"; then
    IMAGE_INSTALLED=true
    echo "[5/5] Existing Debian installation detected in $DISK_NAME"
  else
    echo "[5/5] No existing Debian installation detected in $DISK_NAME"
  fi
fi

QEMU_BASE_CMD=(qemu-system-x86_64
  -name "$VM_NAME"
  -machine accel=kvm
  -cpu host
  -smp "$VCPUS"
  -m "$RAM"
  -drive file="$IMAGE_DIR/$DISK_NAME",if=virtio,format=qcow2
  -display gtk
  -vga qxl
  -nic user,model=virtio,hostfwd=tcp:127.0.0.1:2222-:22
  -device qemu-xhci
)

if [[ -n "$CAMERA_VENDOR_ID" && -n "$CAMERA_PRODUCT_ID" ]]; then
  QEMU_BASE_CMD+=( -device usb-host,vendorid="$CAMERA_VENDOR_ID",productid="$CAMERA_PRODUCT_ID" )
fi

if [[ "$IMAGE_INSTALLED" == true ]]; then
  echo "Existing Debian install detected; booting from disk."
  exec sudo "${QEMU_BASE_CMD[@]}"
fi
run_auto_install
